"""
orchestrator.py — workflow: Support-mailbox-automation
Objective: This workflow addresses the customer inquiry on the orders and respond back to the customer with latest update on the provided order number.
Generated by Agentic Command Center. Edit to customise logic.
"""

import json
import logging
import requests
from datetime import datetime, timezone

from workflow_config import (
    PROJECT_ENDPOINT,
    AZURE_AI_API_KEY,
    AGENT_ID_DETERMINE_THE_EMAIL_INTENT,
    AGENT_VERSION_DETERMINE_THE_EMAIL_INTENT,
    MCP_MYEMAILMCPSERVER_ENDPOINT,
)

from azure.ai.projects import AIProjectClient
from azure.core.credentials import AzureKeyCredential

# Logging is configured by main.py; orchestrator uses a named logger.
logger = logging.getLogger("workflow.orchestrator")

# Structured per-step log — cleared at the start of each run.
_step_logs: list[dict] = []

def get_step_logs() -> list[dict]:
    """Return the accumulated structured step log for the most recent run."""
    return list(_step_logs)

def _log_step(step_name: str, info: str, result: object = None) -> None:
    _step_logs.append({
        "time": datetime.now(timezone.utc).isoformat(),
        "step": step_name,
        "info": info,
        "result": result,
    })

# Azure AI Foundry client — shared across all agent calls
_project_client = AIProjectClient(
    endpoint=PROJECT_ENDPOINT,
    credential=AzureKeyCredential(AZURE_AI_API_KEY),
)

# ---------------------------------------------------------------------------
# Workflow entry point
# ---------------------------------------------------------------------------

def run_workflow(input_data: dict) -> dict:
    """Execute: Support-mailbox-automation"""
    logger.info("Workflow started: Support-mailbox-automation")
    _step_logs.clear()
    data = dict(input_data)
    try:
        data = step_get_unread_emails(data)
        # For-each: For each unread emails
        _for_each_unread_emails_items = _get_items_for_each_unread_emails(data)
        logger.info(f"For-each 'For each unread emails': {len(_for_each_unread_emails_items)} item(s)")
        _for_each_unread_emails_results = []
        for item in _for_each_unread_emails_items:
            data["item"] = item
            data = step_get_email_detail(data)
            data = step_determine_the_email_intent(data)
            if _condition_is_email_about_tracking_order(data):  # Is Email about Tracking Order
                data = step_respond_email(data)
            _for_each_unread_emails_results.append(data.copy())
        data["for_each_unread_emails_results"] = _for_each_unread_emails_results

        logger.info("Workflow completed: Support-mailbox-automation")
        return data
    except Exception as exc:
        logger.error(f"Workflow failed: {exc}", exc_info=True)
        raise

# ---------------------------------------------------------------------------
# Node step functions
# ---------------------------------------------------------------------------

def step_determine_the_email_intent(data: dict) -> dict:
    """Calls Azure AI Foundry agent: Support Email Intent Classifier"""
    logger.info("Step: Determine the email intent")
    try:
        data = _run_agent(AGENT_ID_DETERMINE_THE_EMAIL_INTENT, AGENT_VERSION_DETERMINE_THE_EMAIL_INTENT, data)
        _log_step("Determine the email intent", f"Agent response received; output keys: {list(data.keys())}", result=data)
    except Exception as exc:
        _log_step("Determine the email intent", f"Failed: {exc}", result=str(exc))
        raise
    return data

def step_get_unread_emails(data: dict) -> dict:
    """Calls MCP tool 'list_unread_emails'"""
    logger.info("Step: Get Unread emails")
    args = {}
    try:
        result = _call_mcp_tool(MCP_MYEMAILMCPSERVER_ENDPOINT, "list_unread_emails", args)
        data["get_unread_emails_result"] = result
        logger.info("Step Get Unread emails succeeded")
        _log_step("Get Unread emails", f"Tool 'list_unread_emails' succeeded; result stored in 'get_unread_emails_result'", result=result)
    except Exception as exc:
        logger.error(f"Step Get Unread emails failed: {exc}", exc_info=True)
        _log_step("Get Unread emails", f"Tool 'list_unread_emails' failed: {exc}", result=str(exc))
        data["get_unread_emails_result"] = None
    return data

def step_get_email_detail(data: dict) -> dict:
    """Calls MCP tool 'get_email_by_id'"""
    logger.info("Step: Get Email Detail")
    args = {}
    args["email_id"] = data.get("item", {}).get("id")
    try:
        result = _call_mcp_tool(MCP_MYEMAILMCPSERVER_ENDPOINT, "get_email_by_id", args)
        data["get_email_detail_result"] = result
        logger.info("Step Get Email Detail succeeded")
        _log_step("Get Email Detail", f"Tool 'get_email_by_id' succeeded; result stored in 'get_email_detail_result'", result=result)
    except Exception as exc:
        logger.error(f"Step Get Email Detail failed: {exc}", exc_info=True)
        _log_step("Get Email Detail", f"Tool 'get_email_by_id' failed: {exc}", result=str(exc))
        data["get_email_detail_result"] = None
    return data

def step_respond_email(data: dict) -> dict:
    """Calls MCP tool 'reply_to_email'"""
    logger.info("Step: Respond Email")
    args = {}
    args["email_id"] = data.get("item", {}).get("id")
    args["body"] = "\"Thank You for your inquiry we are processing your request\""
    try:
        result = _call_mcp_tool(MCP_MYEMAILMCPSERVER_ENDPOINT, "reply_to_email", args)
        data["respond_email_result"] = result
        logger.info("Step Respond Email succeeded")
        _log_step("Respond Email", f"Tool 'reply_to_email' succeeded; result stored in 'respond_email_result'", result=result)
    except Exception as exc:
        logger.error(f"Step Respond Email failed: {exc}", exc_info=True)
        _log_step("Respond Email", f"Tool 'reply_to_email' failed: {exc}", result=str(exc))
        data["respond_email_result"] = None
    return data

# ---------------------------------------------------------------------------
# Condition evaluators
# ---------------------------------------------------------------------------

def _condition_is_email_about_tracking_order(data: dict) -> bool:
    """Condition: Is Email about Tracking Order"""
    try:
        return bool(data.get("email_intent") == "Track_Order")
    except Exception as exc:
        logger.warning(f"Condition 'Is Email about Tracking Order' error: {exc} — defaulting False")
        return False

# ---------------------------------------------------------------------------
# For-each helpers
# ---------------------------------------------------------------------------

def _get_items_for_each_unread_emails(data: dict) -> list:
    """Resolve iteration list for: For each unread emails"""
    try:
        mcp_result = data.get("get_unread_emails_result", [])
        if not isinstance(mcp_result, dict):
            return mcp_result if isinstance(mcp_result, list) else ([mcp_result] if mcp_result is not None else [])
        # Extract records from MCP structuredContent.result
        items = mcp_result.get("structuredContent", {}).get("result", [])
        if items:
            return items
        # Fallback: parse content[0].text if structuredContent missing
        content_text = (mcp_result.get("content") or [{}])[0].get("text", "")
        if content_text:
            parsed = json.loads(content_text)
            return parsed if isinstance(parsed, list) else [parsed]
        return []
    except Exception as exc:
        logger.error(f"For-each 'For each unread emails' list error: {exc}")
        return []

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_headers(api_key: str = "") -> dict:
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    return headers

def _run_agent(agent_id: str, agent_version: str, data: dict) -> dict:
    """Call a pre-deployed Azure AI Foundry agent via AIProjectClient SDK."""
    # Build input — send only the current item context, not the entire data blob
    input_messages = [{"role": "user", "content": json.dumps(data, default=str)}]
    agent_reference = {"name": agent_id, "version": agent_version, "type": "agent_reference"}

    logger.info("=" * 60)
    logger.info(f"AI AGENT REQUEST  [{agent_id}  v{agent_version}]")
    logger.info(f"  Endpoint       : {PROJECT_ENDPOINT}")
    logger.info(f"  Agent reference: {json.dumps(agent_reference)}")
    logger.info(f"  Input messages :\n{json.dumps(input_messages, indent=4, default=str)}")
    logger.info("=" * 60)

    # api_key= MUST be passed explicitly — without it get_openai_client()
    # calls get_bearer_token_provider() which fails for AzureKeyCredential.
    openai_client = _project_client.get_openai_client(api_key=AZURE_AI_API_KEY)
    response = openai_client.responses.create(
        input=input_messages,
        extra_body={"agent_reference": agent_reference},
    )
    response_text = response.output_text

    logger.info("=" * 60)
    logger.info(f"AI AGENT RESPONSE [{agent_id}  v{agent_version}]")
    logger.info(f"  Content:\n{response_text}")
    logger.info("=" * 60)

    try:
        parsed = json.loads(response_text)
        if isinstance(parsed, list) and parsed:
            parsed = parsed[0]  # agent returns a list — take first item
        if isinstance(parsed, dict):
            return {**data, **parsed}
        return {**data, "agent_output": parsed}
    except json.JSONDecodeError:
        return {**data, "agent_output": response_text}

# MCP Streamable HTTP transport — required Accept header to avoid 406 responses
_MCP_HEADERS = {
    "Content-Type": "application/json",
    "Accept": "application/json, text/event-stream",
}

def _mcp_post(server_endpoint: str, payload: dict, session_id: str | None = None):
    """POST a JSON-RPC message to an MCP server; handle both JSON and SSE responses."""
    headers = dict(_MCP_HEADERS)
    if session_id:
        headers["Mcp-Session-Id"] = session_id
    response = requests.post(server_endpoint, json=payload, headers=headers, timeout=30)
    response.raise_for_status()
    returned_session_id = response.headers.get("Mcp-Session-Id")
    content_type = response.headers.get("Content-Type", "")
    if "text/event-stream" in content_type:
        for line in response.text.splitlines():
            if line.startswith("data:"):
                data = line[len("data:"):].strip()
                if data and data != "[DONE]":
                    return json.loads(data), returned_session_id
        return {}, returned_session_id
    body = response.json() if response.content else {}
    return body, returned_session_id

def _call_mcp_tool(server_endpoint: str, tool_name: str, args: dict) -> dict:
    """Call an MCP server tool using the full Streamable HTTP 3-step handshake."""
    # Step 1: Initialize — server returns Mcp-Session-Id header
    init_payload = {
        "jsonrpc": "2.0", "id": 0,
        "method": "initialize",
        "params": {
            "protocolVersion": "2024-11-05",
            "capabilities": {},
            "clientInfo": {"name": "workflow-client", "version": "1.0"},
        },
    }
    _, session_id = _mcp_post(server_endpoint, init_payload)
    # Step 2: Send initialized notification (fire-and-forget)
    notif = {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}}
    try:
        _mcp_post(server_endpoint, notif, session_id)
    except Exception:
        pass
    # Step 3: Call the tool
    payload = {
        "jsonrpc": "2.0", "id": 1,
        "method": "tools/call",
        "params": {"name": tool_name, "arguments": args},
    }
    result, _ = _mcp_post(server_endpoint, payload, session_id)
    if "error" in result:
        raise RuntimeError(f"MCP tool error: {result['error']}")
    return result.get("result", {})

# ---------------------------------------------------------------------------
# Cosmos DB tracing helpers (used by run())
# ---------------------------------------------------------------------------

def _get_cosmos_container():
    """Return the Cosmos DB container for execution tracing, or None."""
    from workflow_config import COSMOS_DB_ENDPOINT, COSMOS_DB_DATABASE, COSMOS_DB_KEY, WORKFLOW_ID
    if not (COSMOS_DB_ENDPOINT and COSMOS_DB_DATABASE and COSMOS_DB_KEY and WORKFLOW_ID):
        return None
    try:
        from azure.cosmos import CosmosClient, PartitionKey
        client = CosmosClient(url=COSMOS_DB_ENDPOINT, credential=COSMOS_DB_KEY)
        db = client.get_database_client(COSMOS_DB_DATABASE)
        return db.create_container_if_not_exists(
            id=WORKFLOW_ID,
            partition_key=PartitionKey(path="/date"),
        )
    except Exception as exc:
        logger.warning("Cosmos DB container init failed: %s", exc)
        return None


def _flush_to_cosmos(container, instance_id: str, date_part: str, started_at: str, status: str, step_logs: list) -> None:
    if container is None:
        return
    from datetime import datetime, timezone
    from workflow_config import WORKFLOW_ID, WORKFLOW_NAME
    try:
        doc = {
            "id": instance_id,
            "date": date_part,
            "workflowId": WORKFLOW_ID,
            "workflowName": WORKFLOW_NAME,
            "instanceId": instance_id,
            "startedAt": started_at,
            "completedAt": datetime.now(timezone.utc).isoformat(),
            "status": status,
            "logs": step_logs,
        }
        container.upsert_item(doc)
    except Exception as exc:
        logger.warning("Cosmos DB flush failed: %s", exc)


# ---------------------------------------------------------------------------
# Public entry point — imported by function_app.py
# ---------------------------------------------------------------------------

def run(input_data: dict | None = None) -> dict:
    """
    Execute 'Support-mailbox-automation' with optional input.
    Called by the timer and HTTP triggers in function_app.py.
    Also usable directly:  from orchestrator import run; run()
    """
    from datetime import datetime, timezone
    started_at = datetime.now(timezone.utc).isoformat()
    instance_id = datetime.now(timezone.utc).strftime("%Y-%m-%d:%H-%M-%S")
    date_part = instance_id[:10]
    container = _get_cosmos_container()
    status = "success"
    try:
        result = run_workflow(input_data or {})
        logger.info("Workflow completed: %s", json.dumps(result, default=str)[:300])
        return result
    except Exception as exc:
        status = "error"
        logger.error("Workflow failed: %s", exc, exc_info=True)
        raise
    finally:
        _flush_to_cosmos(container, instance_id, date_part, started_at, status, get_step_logs())


if __name__ == "__main__":
    # Quick local test — invoke directly for debugging.
    # In production, function_app.py is the entry point.
    import json as _json
    print(_json.dumps(run({"_local": True}), indent=2, default=str))
